/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *interface1;
  GtkWidget *authentification;
  GtkWidget *Admin_Space_V2;
  GtkWidget *authentification_client;
  GtkWidget *Client_Space;
  GtkWidget *warning;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //interface1 = create_interface1 ();
  //gtk_widget_show (interface1);
  //authentification = create_authentification ();
  //gtk_widget_show (authentification);
  //Admin_Space_V2 = create_Admin_Space_V2 ();
  //gtk_widget_show (Admin_Space_V2);
 // authentification_client = create_authentification_client ();
  //gtk_widget_show (authentification_client);
  Client_Space = create_Client_Space ();
  gtk_widget_show (Client_Space);
  //warning = create_warning ();
  //gtk_widget_show (warning);


  gtk_main ();
  return 0;
}

